### PR TITLE
Add PSR-17 support

### PR DESCRIPTION
**Pull request by flyinghail**
Add [PSR-17: HTTP Factories](https://www.php-fig.org/psr/psr-17/) support.

PHP package: [psr/http-factory](https://github.com/php-fig/http-factory).

### CODE REVIEW

**Comment by flyinghail** [comment]
Require signed commits... 
I will pull request later.

**Comment by jbboehr** [comment]
@flyinghail Sorry, I'll turn it off. It was supposed to make sure I always used signed commits, I guess it makes sense the setting should apply to PRs also...

**Comment by jbboehr** [comment]
cc @sergeyklay if you want to review

**Review by sergeyklay — APPROVED** [review]
Looks good to me!

**Comment by jbboehr** [comment]
LGTM as well. Thanks!

**Pull request closed without merging**
