### PR TITLE
Add PSR-18 support

### PR DESCRIPTION
**Pull request by flyinghail**
Add [PSR-18: HTTP Client](https://www.php-fig.org/psr/psr-18/) support.

PHP package: [psr/http-client](https://github.com/php-fig/http-client/).

### CODE REVIEW

**Comment by flyinghail** [comment]
The library I used to test PSR-18 [ricardofiorani/guzzle-psr18-adapter](https://github.com/ricardofiorani/guzzle-psr18-adapter) requires PHP >= 7.1.

Another library I found that support PSR-18 [php-http/curl-client](https://github.com/php-http/curl-client) (with [php-http/httplug v2.0.0](https://packagist.org/packages/php-http/httplug#v2.0.0)) also requires PHP >= 7.1

It will take some time to wait for other client libraries to support PSR-18.

**Comment by sergeyklay** [comment]
It seems to me we can just skip tests PSR-18 on PHP 7.0 in case of absence a PHP 7.0 compatible library. But first we need to make sure of it. 

@jbboehr Thoughts?

**Comment by jbboehr** [comment]
That works for me. I've also been eyeing that 7.0 EOL in one month.

**Comment by jbboehr** [comment]
Looks good, thanks!

**Pull request merged**
