### PR TITLE
Fixed AppVeyor build

### PR DESCRIPTION
**Pull request by sergeyklay**
Hello @jbboehr 

What I suggest:

* Don't test PHP 7.2 until SDK for 7.2 was released. See: http://windows.php.net/downloads/php-sdk
* Fix indents regarding to `.editorconfig`
* Test x86 as well as x64
* Prepare ready do use DLLs for TS and NTS versions

---

Refs: #23

### CODE REVIEW

**Comment by sergeyklay** [comment]
As I can see everything is ok for Windows :)

**Comment by sergeyklay** [comment]
Just for clarification: I'm not sure that there is any real needs to run unit tests twice - first time at Travis CI and second one at AppVeyor. The only real reason using AppVeyor  is to make sure that the build process is fine on Windows.

**Comment by jbboehr** [comment]
@sergeyklay They say they are no longer going to provide the deps as a single archive:

> Note the .7z packages are not provided anymore for PHP 7.2 and up.

https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2

**Comment by sergeyklay** [comment]
@jbboehr Anyway I suggest to postpone the PHP 7.2 issue because it blocks https://github.com/jbboehr/php-psr/pull/22. We'll sort out with 7.2 a bit later

**Pull request closed without merging**
